// Copyright 2025 URAV ADVANCED LEARNING SYSTEMS PRIVATE LIMITED
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using UnityEngine;
using Uralstech.Utils.Singleton;

#nullable enable
namespace Uralstech.UXR.QuestCamera
{
    /// <summary>
    /// Class for interfacing with the native Camera2 API on Android.
    /// </summary>
    [AddComponentMenu("Uralstech/UXR/Quest Camera/Quest Camera Manager")]
    public class UCameraManager : DontCreateNewSingleton<UCameraManager>
    {
        /// <summary>
        /// The permission required to access the Meta Quest's Passthrough cameras.
        /// </summary>
        public const string HeadsetCameraPermission = "horizonos.permission.HEADSET_CAMERA";

        /// <summary>
        /// The permission required to access the Meta Quest's avatar camera.
        /// </summary>
        public const string AvatarCameraPermission = "android.permission.CAMERA";

        /// <summary>
        /// The compute shader to use to convert the camera's YUV 4:2:0 images to RGBA.
        /// </summary>
        [Tooltip("The compute shader to use to convert the camera's YUV 4:2:0 images to RGBA.")]
        public ComputeShader YUVToRGBAComputeShader;

        /// <summary>
        /// Gets a cached array of the available cameras and their characteristics.
        /// </summary>
        /// <remarks>
        /// The disposal of the <see cref="CameraInfo"/> objects generated by this property
        /// are managed by the <see cref="UCameraManager"/> instance. If you require control
        /// of the <see cref="CameraInfo"/> objects, use <see cref="GetCameraInfos"/> instead.
        /// </remarks>
        public CameraInfo[]? Cameras => _cameraInfosCached is not null ? _cameraInfosCached : (_cameraInfosCached = GetCameraInfos());

        private CameraInfo[]? _cameraInfosCached = null;
        private AndroidJavaObject? _camera2Wrapper;

        protected override void Awake()
        {
            base.Awake();
            DontDestroyOnLoad(gameObject);

            using AndroidJavaClass camera2WrapperClass = new("com.uralstech.ucamera.Camera2Wrapper");
            _camera2Wrapper = camera2WrapperClass.CallStatic<AndroidJavaObject>("getInstance");
        }

        protected void OnDestroy()
        {
            ClearAndDisposeCameraInfos();
            _camera2Wrapper?.Dispose();
            _camera2Wrapper = null;
        }

        /// <summary>
        /// Refreshes the cached array of camera devices.
        /// </summary>
        /// <returns><see langword="true"/> if the refresh was successful; <see langword="false"/> otherwise.</returns>
        public bool RefreshCachedCameraInfos()
        {
            ClearAndDisposeCameraInfos();
            return (_cameraInfosCached = GetCameraInfos()) != null;
        }
        
        private void ClearAndDisposeCameraInfos()
        {
            if (_cameraInfosCached is not null)
            {
                int cameraInfoCount = _cameraInfosCached.Length;
                for (int i = 0; i < cameraInfoCount; i++)
                    _cameraInfosCached[i].Dispose();

                _cameraInfosCached = null;
            }
        }

        /// <summary>
        /// Gets all available cameras and their characteristics. This is <b>not</b> cached.
        /// </summary>
        /// <remarks>
        /// You will have to manage the disposal of the <see cref="CameraInfo"/> objects
        /// returned by this method. Use <see cref="Cameras"/> if you don't want to handle
        /// the objects yourself.
        /// </remarks>
        /// <returns>An array of <see cref="CameraInfo"/> objects or <see langword="null"/> if any errors occurred.</returns>
        public CameraInfo[]? GetCameraInfos()
        {
            AndroidJavaObject[]? nativeObjects = _camera2Wrapper?.Call<AndroidJavaObject[]>("getCameraDevices");
            if (nativeObjects is null)
            {
                Debug.LogError("Could not get camera device information.");
                return null;
            }

            int count = nativeObjects.Length;
            CameraInfo[] wrappers = new CameraInfo[count];

            for (int i = 0; i < count; i++)
            {
                AndroidJavaObject nativeObj = nativeObjects[i];
                wrappers[i] = new CameraInfo(nativeObj);
                nativeObj.Dispose();
            }

            return wrappers;
        }

        /// <summary>
        /// Gets a camera device by the eye it is closest to.
        /// </summary>
        /// <param name="eye">The eye.</param>
        /// <returns>A <see cref="CameraInfo"/> object or <see langword="null"/> if none were found.</returns>
        public CameraInfo? GetCamera(CameraInfo.CameraEye eye)
        {
            if (Cameras is CameraInfo[] cameras)
            {
                foreach (CameraInfo cameraInfo in cameras)
                {
                    if (cameraInfo.Eye == eye)
                        return cameraInfo;
                }
            }
            
            return null;
        }

        /// <summary>
        /// Opens a camera device for use.
        /// </summary>
        /// <remarks>
        /// Once you have finished using the camera, close and dispose of it using <see cref="CameraDevice.Dispose()"/>.
        /// </remarks>
        /// <param name="camera">The ID of the camera to open; accepts <see cref="CameraInfo"/> objects through an implicit cast.</param>
        /// <returns>A <see cref="CameraDevice"/> object or <see langword="null"/> if any errors occurred.</returns>
        public CameraDevice? OpenCamera(string camera)
        {
            CameraDevice cameraDevice = new(camera);
            AndroidJavaObject? nativeObject = _camera2Wrapper?.Call<AndroidJavaObject>("openCameraDevice", camera, cameraDevice);
            if (nativeObject is null)
            {
                cameraDevice.Dispose();
                return null;
            }

            cameraDevice._cameraDevice = nativeObject;
            return cameraDevice;
        }
    }
}